<?php
/**
 * InboundShipmentStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for Amazon Warehousing and Distribution
 *
 * The Selling Partner API for Amazon Warehousing and Distribution (AWD) provides programmatic access to information about AWD shipments and inventory.
 *
 * OpenAPI spec version: 2024-05-09
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\Awd20240509;
use \SellingPartnerApi\ObjectSerializer;

/**
 * InboundShipmentStatus Class Doc Comment
 *
 * @category Class
 * @description Possible shipment statuses used by shipments.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundShipmentStatus
{
    /**
     * Possible values of this enum
     */
    const CREATED = 'CREATED';
    const SHIPPED = 'SHIPPED';
    const IN_TRANSIT = 'IN_TRANSIT';
    const RECEIVING = 'RECEIVING';
    const DELIVERED = 'DELIVERED';
    const CLOSED = 'CLOSED';
    const CANCELLED = 'CANCELLED';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::SHIPPED,
            self::IN_TRANSIT,
            self::RECEIVING,
            self::DELIVERED,
            self::CLOSED,
            self::CANCELLED
        ];
    }
}
