<?php
/**
 * CreateSupplySourceResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * OpenAPI spec version: 2020-07-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\SupplySources20200701;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * CreateSupplySourceResponse Class Doc Comment
 *
 * @category Class
 * @description The result of creating a new supply source.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateSupplySourceResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateSupplySourceResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'supplySourceId' => '\SellingPartnerApi\Model\SupplySources20200701\SupplySourceId',
        'supplySourceCode' => '\SellingPartnerApi\Model\SupplySources20200701\SupplySourceCode'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'supplySourceId' => null,
        'supplySourceCode' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'supplySourceId' => 'supplySourceId',
        'supplySourceCode' => 'supplySourceCode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'supplySourceId' => 'setSupplySourceId',
        'supplySourceCode' => 'setSupplySourceCode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'supplySourceId' => 'getSupplySourceId',
        'supplySourceCode' => 'getSupplySourceCode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['supplySourceId'] = isset($data['supplySourceId']) ? $data['supplySourceId'] : null;
        $this->container['supplySourceCode'] = isset($data['supplySourceCode']) ? $data['supplySourceCode'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['supplySourceId'] === null) {
            $invalidProperties[] = "'supplySourceId' can't be null";
        }
        if ($this->container['supplySourceCode'] === null) {
            $invalidProperties[] = "'supplySourceCode' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets supplySourceId
     *
     * @return \SellingPartnerApi\Model\SupplySources20200701\SupplySourceId
     */
    public function getSupplySourceId()
    {
        return $this->container['supplySourceId'];
    }

    /**
     * Sets supplySourceId
     *
     * @param \SellingPartnerApi\Model\SupplySources20200701\SupplySourceId $supplySourceId supplySourceId
     *
     * @return $this
     */
    public function setSupplySourceId($supplySourceId)
    {
        $this->container['supplySourceId'] = $supplySourceId;

        return $this;
    }

    /**
     * Gets supplySourceCode
     *
     * @return \SellingPartnerApi\Model\SupplySources20200701\SupplySourceCode
     */
    public function getSupplySourceCode()
    {
        return $this->container['supplySourceCode'];
    }

    /**
     * Sets supplySourceCode
     *
     * @param \SellingPartnerApi\Model\SupplySources20200701\SupplySourceCode $supplySourceCode supplySourceCode
     *
     * @return $this
     */
    public function setSupplySourceCode($supplySourceCode)
    {
        $this->container['supplySourceCode'] = $supplySourceCode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
