<?php
/**
 * MarketplaceChannelDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for Amazon External Fulfillment Return Item Processing
 *
 * You can use the Amazon External Fulfillment Return Item Processing API to retrieve, track, and process return items through Amazon's External Fulfillment returns management system.
 *
 * OpenAPI spec version: 2024-09-11
 * Contact: marketplaceapitest@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\ExternalFulfillmentReturns20240911;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * MarketplaceChannelDetails Class Doc Comment
 *
 * @category Class
 * @description Marketplace channel-specific attributes for the return. These attributes are not mandatory and each channel can provide them differently.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketplaceChannelDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MarketplaceChannelDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'marketplaceChannel' => '\SellingPartnerApi\Model\ExternalFulfillmentReturns20240911\MarketplaceChannel',
        'merchantId' => 'string',
        'shipmentId' => 'string',
        'customerOrderId' => 'string',
        'returnLocationId' => 'string',
        'channelSku' => 'string',
        'exchangeOrderId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'marketplaceChannel' => null,
        'merchantId' => null,
        'shipmentId' => null,
        'customerOrderId' => null,
        'returnLocationId' => null,
        'channelSku' => null,
        'exchangeOrderId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'marketplaceChannel' => 'marketplaceChannel',
        'merchantId' => 'merchantId',
        'shipmentId' => 'shipmentId',
        'customerOrderId' => 'customerOrderId',
        'returnLocationId' => 'returnLocationId',
        'channelSku' => 'channelSku',
        'exchangeOrderId' => 'exchangeOrderId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'marketplaceChannel' => 'setMarketplaceChannel',
        'merchantId' => 'setMerchantId',
        'shipmentId' => 'setShipmentId',
        'customerOrderId' => 'setCustomerOrderId',
        'returnLocationId' => 'setReturnLocationId',
        'channelSku' => 'setChannelSku',
        'exchangeOrderId' => 'setExchangeOrderId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'marketplaceChannel' => 'getMarketplaceChannel',
        'merchantId' => 'getMerchantId',
        'shipmentId' => 'getShipmentId',
        'customerOrderId' => 'getCustomerOrderId',
        'returnLocationId' => 'getReturnLocationId',
        'channelSku' => 'getChannelSku',
        'exchangeOrderId' => 'getExchangeOrderId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['marketplaceChannel'] = isset($data['marketplaceChannel']) ? $data['marketplaceChannel'] : null;
        $this->container['merchantId'] = isset($data['merchantId']) ? $data['merchantId'] : null;
        $this->container['shipmentId'] = isset($data['shipmentId']) ? $data['shipmentId'] : null;
        $this->container['customerOrderId'] = isset($data['customerOrderId']) ? $data['customerOrderId'] : null;
        $this->container['returnLocationId'] = isset($data['returnLocationId']) ? $data['returnLocationId'] : null;
        $this->container['channelSku'] = isset($data['channelSku']) ? $data['channelSku'] : null;
        $this->container['exchangeOrderId'] = isset($data['exchangeOrderId']) ? $data['exchangeOrderId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets marketplaceChannel
     *
     * @return \SellingPartnerApi\Model\ExternalFulfillmentReturns20240911\MarketplaceChannel
     */
    public function getMarketplaceChannel()
    {
        return $this->container['marketplaceChannel'];
    }

    /**
     * Sets marketplaceChannel
     *
     * @param \SellingPartnerApi\Model\ExternalFulfillmentReturns20240911\MarketplaceChannel $marketplaceChannel marketplaceChannel
     *
     * @return $this
     */
    public function setMarketplaceChannel($marketplaceChannel)
    {
        $this->container['marketplaceChannel'] = $marketplaceChannel;

        return $this;
    }

    /**
     * Gets merchantId
     *
     * @return string
     */
    public function getMerchantId()
    {
        return $this->container['merchantId'];
    }

    /**
     * Sets merchantId
     *
     * @param string $merchantId The ID of the merchant or seller to whom this return is created in the marketplace.
     *
     * @return $this
     */
    public function setMerchantId($merchantId)
    {
        $this->container['merchantId'] = $merchantId;

        return $this;
    }

    /**
     * Gets shipmentId
     *
     * @return string
     */
    public function getShipmentId()
    {
        return $this->container['shipmentId'];
    }

    /**
     * Sets shipmentId
     *
     * @param string $shipmentId The marketplace-specific shipment ID.
     *
     * @return $this
     */
    public function setShipmentId($shipmentId)
    {
        $this->container['shipmentId'] = $shipmentId;

        return $this;
    }

    /**
     * Gets customerOrderId
     *
     * @return string
     */
    public function getCustomerOrderId()
    {
        return $this->container['customerOrderId'];
    }

    /**
     * Sets customerOrderId
     *
     * @param string $customerOrderId The marketplace-specific customer order ID.
     *
     * @return $this
     */
    public function setCustomerOrderId($customerOrderId)
    {
        $this->container['customerOrderId'] = $customerOrderId;

        return $this;
    }

    /**
     * Gets returnLocationId
     *
     * @return string
     */
    public function getReturnLocationId()
    {
        return $this->container['returnLocationId'];
    }

    /**
     * Sets returnLocationId
     *
     * @param string $returnLocationId The Amazon SmartConnect ID of the location to which this return is created.
     *
     * @return $this
     */
    public function setReturnLocationId($returnLocationId)
    {
        $this->container['returnLocationId'] = $returnLocationId;

        return $this;
    }

    /**
     * Gets channelSku
     *
     * @return string
     */
    public function getChannelSku()
    {
        return $this->container['channelSku'];
    }

    /**
     * Sets channelSku
     *
     * @param string $channelSku The Amazon SmartConnect SKU of the channel.
     *
     * @return $this
     */
    public function setChannelSku($channelSku)
    {
        $this->container['channelSku'] = $channelSku;

        return $this;
    }

    /**
     * Gets exchangeOrderId
     *
     * @return string
     */
    public function getExchangeOrderId()
    {
        return $this->container['exchangeOrderId'];
    }

    /**
     * Sets exchangeOrderId
     *
     * @param string $exchangeOrderId The Amazon SmartConnect ID of the exchange order.
     *
     * @return $this
     */
    public function setExchangeOrderId($exchangeOrderId)
    {
        $this->container['exchangeOrderId'] = $exchangeOrderId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
