<?php
/**
 * CreateMarketplaceItemLabelsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\FulfillmentInbound20240320;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * CreateMarketplaceItemLabelsRequest Class Doc Comment
 *
 * @category Class
 * @description The &#x60;createMarketplaceItemLabels&#x60; request.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateMarketplaceItemLabelsRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateMarketplaceItemLabelsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'height' => 'float',
        'labelType' => '\SellingPartnerApi\Model\FulfillmentInbound20240320\LabelPrintType',
        'localeCode' => 'string',
        'marketplaceId' => 'string',
        'mskuQuantities' => '\SellingPartnerApi\Model\FulfillmentInbound20240320\MskuQuantity[]',
        'pageType' => '\SellingPartnerApi\Model\FulfillmentInbound20240320\ItemLabelPageType',
        'width' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'height' => null,
        'labelType' => null,
        'localeCode' => null,
        'marketplaceId' => null,
        'mskuQuantities' => null,
        'pageType' => null,
        'width' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'height' => 'height',
        'labelType' => 'labelType',
        'localeCode' => 'localeCode',
        'marketplaceId' => 'marketplaceId',
        'mskuQuantities' => 'mskuQuantities',
        'pageType' => 'pageType',
        'width' => 'width'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'height' => 'setHeight',
        'labelType' => 'setLabelType',
        'localeCode' => 'setLocaleCode',
        'marketplaceId' => 'setMarketplaceId',
        'mskuQuantities' => 'setMskuQuantities',
        'pageType' => 'setPageType',
        'width' => 'setWidth'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'height' => 'getHeight',
        'labelType' => 'getLabelType',
        'localeCode' => 'getLocaleCode',
        'marketplaceId' => 'getMarketplaceId',
        'mskuQuantities' => 'getMskuQuantities',
        'pageType' => 'getPageType',
        'width' => 'getWidth'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['labelType'] = isset($data['labelType']) ? $data['labelType'] : null;
        $this->container['localeCode'] = isset($data['localeCode']) ? $data['localeCode'] : 'en_US';
        $this->container['marketplaceId'] = isset($data['marketplaceId']) ? $data['marketplaceId'] : null;
        $this->container['mskuQuantities'] = isset($data['mskuQuantities']) ? $data['mskuQuantities'] : null;
        $this->container['pageType'] = isset($data['pageType']) ? $data['pageType'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['labelType'] === null) {
            $invalidProperties[] = "'labelType' can't be null";
        }
        if ($this->container['marketplaceId'] === null) {
            $invalidProperties[] = "'marketplaceId' can't be null";
        }
        if ($this->container['mskuQuantities'] === null) {
            $invalidProperties[] = "'mskuQuantities' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets height
     *
     * @return float
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param float $height The height of the item label.
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets labelType
     *
     * @return \SellingPartnerApi\Model\FulfillmentInbound20240320\LabelPrintType
     */
    public function getLabelType()
    {
        return $this->container['labelType'];
    }

    /**
     * Sets labelType
     *
     * @param \SellingPartnerApi\Model\FulfillmentInbound20240320\LabelPrintType $labelType labelType
     *
     * @return $this
     */
    public function setLabelType($labelType)
    {
        $this->container['labelType'] = $labelType;

        return $this;
    }

    /**
     * Gets localeCode
     *
     * @return string
     */
    public function getLocaleCode()
    {
        return $this->container['localeCode'];
    }

    /**
     * Sets localeCode
     *
     * @param string $localeCode The locale code constructed from ISO 639 language code and ISO 3166-1 alpha-2 standard of country codes separated by an underscore character.
     *
     * @return $this
     */
    public function setLocaleCode($localeCode)
    {
        $this->container['localeCode'] = $localeCode;

        return $this;
    }

    /**
     * Gets marketplaceId
     *
     * @return string
     */
    public function getMarketplaceId()
    {
        return $this->container['marketplaceId'];
    }

    /**
     * Sets marketplaceId
     *
     * @param string $marketplaceId The Marketplace ID. For a list of possible values, refer to [Marketplace IDs](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
     *
     * @return $this
     */
    public function setMarketplaceId($marketplaceId)
    {
        $this->container['marketplaceId'] = $marketplaceId;

        return $this;
    }

    /**
     * Gets mskuQuantities
     *
     * @return \SellingPartnerApi\Model\FulfillmentInbound20240320\MskuQuantity[]
     */
    public function getMskuQuantities()
    {
        return $this->container['mskuQuantities'];
    }

    /**
     * Sets mskuQuantities
     *
     * @param \SellingPartnerApi\Model\FulfillmentInbound20240320\MskuQuantity[] $mskuQuantities Represents the quantity of an MSKU to print item labels for.
     *
     * @return $this
     */
    public function setMskuQuantities($mskuQuantities)
    {
        $this->container['mskuQuantities'] = $mskuQuantities;

        return $this;
    }

    /**
     * Gets pageType
     *
     * @return \SellingPartnerApi\Model\FulfillmentInbound20240320\ItemLabelPageType
     */
    public function getPageType()
    {
        return $this->container['pageType'];
    }

    /**
     * Sets pageType
     *
     * @param \SellingPartnerApi\Model\FulfillmentInbound20240320\ItemLabelPageType $pageType pageType
     *
     * @return $this
     */
    public function setPageType($pageType)
    {
        $this->container['pageType'] = $pageType;

        return $this;
    }

    /**
     * Gets width
     *
     * @return float
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param float $width The width of the item label.
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
