<?php
/**
 * ChannelDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Amazon Shipping API
 *
 * The Amazon Shipping API is designed to support outbound shipping use cases both for orders originating on Amazon-owned marketplaces as well as external channels/marketplaces. With these APIs, you can request shipping rates, create shipments, cancel shipments, and track shipments.
 *
 * OpenAPI spec version: v2
 * Contact: swa-api-core@amazon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\ShippingV2;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * ChannelDetails Class Doc Comment
 *
 * @category Class
 * @description Shipment source channel related information.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChannelDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ChannelDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'channelType' => '\SellingPartnerApi\Model\ShippingV2\ChannelType',
        'amazonOrderDetails' => '\SellingPartnerApi\Model\ShippingV2\AmazonOrderDetails',
        'amazonShipmentDetails' => '\SellingPartnerApi\Model\ShippingV2\AmazonShipmentDetails'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'channelType' => null,
        'amazonOrderDetails' => null,
        'amazonShipmentDetails' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channelType' => 'channelType',
        'amazonOrderDetails' => 'amazonOrderDetails',
        'amazonShipmentDetails' => 'amazonShipmentDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channelType' => 'setChannelType',
        'amazonOrderDetails' => 'setAmazonOrderDetails',
        'amazonShipmentDetails' => 'setAmazonShipmentDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channelType' => 'getChannelType',
        'amazonOrderDetails' => 'getAmazonOrderDetails',
        'amazonShipmentDetails' => 'getAmazonShipmentDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['channelType'] = isset($data['channelType']) ? $data['channelType'] : null;
        $this->container['amazonOrderDetails'] = isset($data['amazonOrderDetails']) ? $data['amazonOrderDetails'] : null;
        $this->container['amazonShipmentDetails'] = isset($data['amazonShipmentDetails']) ? $data['amazonShipmentDetails'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['channelType'] === null) {
            $invalidProperties[] = "'channelType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channelType
     *
     * @return \SellingPartnerApi\Model\ShippingV2\ChannelType
     */
    public function getChannelType()
    {
        return $this->container['channelType'];
    }

    /**
     * Sets channelType
     *
     * @param \SellingPartnerApi\Model\ShippingV2\ChannelType $channelType channelType
     *
     * @return $this
     */
    public function setChannelType($channelType)
    {
        $this->container['channelType'] = $channelType;

        return $this;
    }

    /**
     * Gets amazonOrderDetails
     *
     * @return \SellingPartnerApi\Model\ShippingV2\AmazonOrderDetails
     */
    public function getAmazonOrderDetails()
    {
        return $this->container['amazonOrderDetails'];
    }

    /**
     * Sets amazonOrderDetails
     *
     * @param \SellingPartnerApi\Model\ShippingV2\AmazonOrderDetails $amazonOrderDetails amazonOrderDetails
     *
     * @return $this
     */
    public function setAmazonOrderDetails($amazonOrderDetails)
    {
        $this->container['amazonOrderDetails'] = $amazonOrderDetails;

        return $this;
    }

    /**
     * Gets amazonShipmentDetails
     *
     * @return \SellingPartnerApi\Model\ShippingV2\AmazonShipmentDetails
     */
    public function getAmazonShipmentDetails()
    {
        return $this->container['amazonShipmentDetails'];
    }

    /**
     * Sets amazonShipmentDetails
     *
     * @param \SellingPartnerApi\Model\ShippingV2\AmazonShipmentDetails $amazonShipmentDetails amazonShipmentDetails
     *
     * @return $this
     */
    public function setAmazonShipmentDetails($amazonShipmentDetails)
    {
        $this->container['amazonShipmentDetails'] = $amazonShipmentDetails;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
