<?php
/**
 * FeaturedBuyingOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, refer to the [Product Pricing v2022-05-01 Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-05-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\ProductPricing20220501;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * FeaturedBuyingOption Class Doc Comment
 *
 * @category Class
 * @description Describes a featured buying option, which includes a list of segmented featured offers for a particular item condition.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FeaturedBuyingOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FeaturedBuyingOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'buyingOptionType' => 'string',
        'segmentedFeaturedOffers' => '\SellingPartnerApi\Model\ProductPricing20220501\SegmentedFeaturedOffer[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'buyingOptionType' => null,
        'segmentedFeaturedOffers' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buyingOptionType' => 'buyingOptionType',
        'segmentedFeaturedOffers' => 'segmentedFeaturedOffers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buyingOptionType' => 'setBuyingOptionType',
        'segmentedFeaturedOffers' => 'setSegmentedFeaturedOffers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buyingOptionType' => 'getBuyingOptionType',
        'segmentedFeaturedOffers' => 'getSegmentedFeaturedOffers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const BUYING_OPTION_TYPE__NEW = 'New';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBuyingOptionTypeAllowableValues()
    {
        return [
            self::BUYING_OPTION_TYPE__NEW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buyingOptionType'] = isset($data['buyingOptionType']) ? $data['buyingOptionType'] : null;
        $this->container['segmentedFeaturedOffers'] = isset($data['segmentedFeaturedOffers']) ? $data['segmentedFeaturedOffers'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['buyingOptionType'] === null) {
            $invalidProperties[] = "'buyingOptionType' can't be null";
        }
        $allowedValues = $this->getBuyingOptionTypeAllowableValues();
        if (!is_null($this->container['buyingOptionType']) && !in_array($this->container['buyingOptionType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'buyingOptionType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['segmentedFeaturedOffers'] === null) {
            $invalidProperties[] = "'segmentedFeaturedOffers' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buyingOptionType
     *
     * @return string
     */
    public function getBuyingOptionType()
    {
        return $this->container['buyingOptionType'];
    }

    /**
     * Sets buyingOptionType
     *
     * @param string $buyingOptionType The buying option type for the featured offer. `buyingOptionType` represents the buying options that a customer receives on the detail page, such as `B2B`, `Fresh`, and `Subscribe n Save`. `buyingOptionType` currently supports `NEW` as a value.
     *
     * @return $this
     */
    public function setBuyingOptionType($buyingOptionType)
    {
        $allowedValues = $this->getBuyingOptionTypeAllowableValues();
        if (!in_array($buyingOptionType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'buyingOptionType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['buyingOptionType'] = $buyingOptionType;

        return $this;
    }

    /**
     * Gets segmentedFeaturedOffers
     *
     * @return \SellingPartnerApi\Model\ProductPricing20220501\SegmentedFeaturedOffer[]
     */
    public function getSegmentedFeaturedOffers()
    {
        return $this->container['segmentedFeaturedOffers'];
    }

    /**
     * Sets segmentedFeaturedOffers
     *
     * @param \SellingPartnerApi\Model\ProductPricing20220501\SegmentedFeaturedOffer[] $segmentedFeaturedOffers A list of segmented featured offers for the current buying option type. A segment can be considered as a group of regional contexts that all have the same featured offer. A regional context is a combination of factors such as customer type, region, or postal code and buying option.
     *
     * @return $this
     */
    public function setSegmentedFeaturedOffers($segmentedFeaturedOffers)
    {
        $this->container['segmentedFeaturedOffers'] = $segmentedFeaturedOffers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
