<?php
/**
 * PayeeContactInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\SellerWallet20240301;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * PayeeContactInformation Class Doc Comment
 *
 * @category Class
 * @description The contact information of the payee. This field is required when the request &#x60;bankAccountOwnershipType&#x60; is &#x60;THIRD_PARTY&#x60;. The contact information is used for payee verification and registration purposes.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PayeeContactInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PayeeContactInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'payeeFirstName' => 'string',
        'payeeMiddleName' => 'string',
        'payeeLastName' => 'string',
        'addressLine1' => 'string',
        'addressLine2' => 'string',
        'city' => 'string',
        'state' => 'string',
        'postalCode' => 'string',
        'country' => 'string',
        'countryCode' => 'string',
        'emailAddress' => 'string',
        'phoneNumber' => 'string',
        'payeeEntityType' => '\SellingPartnerApi\Model\SellerWallet20240301\PayeeEntityType'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'payeeFirstName' => null,
        'payeeMiddleName' => null,
        'payeeLastName' => null,
        'addressLine1' => null,
        'addressLine2' => null,
        'city' => null,
        'state' => null,
        'postalCode' => null,
        'country' => null,
        'countryCode' => null,
        'emailAddress' => null,
        'phoneNumber' => null,
        'payeeEntityType' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payeeFirstName' => 'payeeFirstName',
        'payeeMiddleName' => 'payeeMiddleName',
        'payeeLastName' => 'payeeLastName',
        'addressLine1' => 'addressLine1',
        'addressLine2' => 'addressLine2',
        'city' => 'city',
        'state' => 'state',
        'postalCode' => 'postalCode',
        'country' => 'country',
        'countryCode' => 'countryCode',
        'emailAddress' => 'emailAddress',
        'phoneNumber' => 'phoneNumber',
        'payeeEntityType' => 'payeeEntityType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payeeFirstName' => 'setPayeeFirstName',
        'payeeMiddleName' => 'setPayeeMiddleName',
        'payeeLastName' => 'setPayeeLastName',
        'addressLine1' => 'setAddressLine1',
        'addressLine2' => 'setAddressLine2',
        'city' => 'setCity',
        'state' => 'setState',
        'postalCode' => 'setPostalCode',
        'country' => 'setCountry',
        'countryCode' => 'setCountryCode',
        'emailAddress' => 'setEmailAddress',
        'phoneNumber' => 'setPhoneNumber',
        'payeeEntityType' => 'setPayeeEntityType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payeeFirstName' => 'getPayeeFirstName',
        'payeeMiddleName' => 'getPayeeMiddleName',
        'payeeLastName' => 'getPayeeLastName',
        'addressLine1' => 'getAddressLine1',
        'addressLine2' => 'getAddressLine2',
        'city' => 'getCity',
        'state' => 'getState',
        'postalCode' => 'getPostalCode',
        'country' => 'getCountry',
        'countryCode' => 'getCountryCode',
        'emailAddress' => 'getEmailAddress',
        'phoneNumber' => 'getPhoneNumber',
        'payeeEntityType' => 'getPayeeEntityType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['payeeFirstName'] = isset($data['payeeFirstName']) ? $data['payeeFirstName'] : null;
        $this->container['payeeMiddleName'] = isset($data['payeeMiddleName']) ? $data['payeeMiddleName'] : null;
        $this->container['payeeLastName'] = isset($data['payeeLastName']) ? $data['payeeLastName'] : null;
        $this->container['addressLine1'] = isset($data['addressLine1']) ? $data['addressLine1'] : null;
        $this->container['addressLine2'] = isset($data['addressLine2']) ? $data['addressLine2'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['postalCode'] = isset($data['postalCode']) ? $data['postalCode'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['countryCode'] = isset($data['countryCode']) ? $data['countryCode'] : null;
        $this->container['emailAddress'] = isset($data['emailAddress']) ? $data['emailAddress'] : null;
        $this->container['phoneNumber'] = isset($data['phoneNumber']) ? $data['phoneNumber'] : null;
        $this->container['payeeEntityType'] = isset($data['payeeEntityType']) ? $data['payeeEntityType'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payeeFirstName'] === null) {
            $invalidProperties[] = "'payeeFirstName' can't be null";
        }
        if ($this->container['payeeLastName'] === null) {
            $invalidProperties[] = "'payeeLastName' can't be null";
        }
        if ($this->container['addressLine1'] === null) {
            $invalidProperties[] = "'addressLine1' can't be null";
        }
        if ($this->container['city'] === null) {
            $invalidProperties[] = "'city' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        if ($this->container['postalCode'] === null) {
            $invalidProperties[] = "'postalCode' can't be null";
        }
        if ($this->container['countryCode'] === null) {
            $invalidProperties[] = "'countryCode' can't be null";
        }
        if ($this->container['emailAddress'] === null) {
            $invalidProperties[] = "'emailAddress' can't be null";
        }
        if ($this->container['phoneNumber'] === null) {
            $invalidProperties[] = "'phoneNumber' can't be null";
        }
        if ($this->container['payeeEntityType'] === null) {
            $invalidProperties[] = "'payeeEntityType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payeeFirstName
     *
     * @return string
     */
    public function getPayeeFirstName()
    {
        return $this->container['payeeFirstName'];
    }

    /**
     * Sets payeeFirstName
     *
     * @param string $payeeFirstName First name of the payee. There is a 50 character limit.
     *
     * @return $this
     */
    public function setPayeeFirstName($payeeFirstName)
    {
        $this->container['payeeFirstName'] = $payeeFirstName;

        return $this;
    }

    /**
     * Gets payeeMiddleName
     *
     * @return string
     */
    public function getPayeeMiddleName()
    {
        return $this->container['payeeMiddleName'];
    }

    /**
     * Sets payeeMiddleName
     *
     * @param string $payeeMiddleName Middle name of the payee. There is a 50 character limit.
     *
     * @return $this
     */
    public function setPayeeMiddleName($payeeMiddleName)
    {
        $this->container['payeeMiddleName'] = $payeeMiddleName;

        return $this;
    }

    /**
     * Gets payeeLastName
     *
     * @return string
     */
    public function getPayeeLastName()
    {
        return $this->container['payeeLastName'];
    }

    /**
     * Sets payeeLastName
     *
     * @param string $payeeLastName Last name of the payee. There is a 50 character limit.
     *
     * @return $this
     */
    public function setPayeeLastName($payeeLastName)
    {
        $this->container['payeeLastName'] = $payeeLastName;

        return $this;
    }

    /**
     * Gets addressLine1
     *
     * @return string
     */
    public function getAddressLine1()
    {
        return $this->container['addressLine1'];
    }

    /**
     * Sets addressLine1
     *
     * @param string $addressLine1 Address Line 1 of the public address
     *
     * @return $this
     */
    public function setAddressLine1($addressLine1)
    {
        $this->container['addressLine1'] = $addressLine1;

        return $this;
    }

    /**
     * Gets addressLine2
     *
     * @return string
     */
    public function getAddressLine2()
    {
        return $this->container['addressLine2'];
    }

    /**
     * Sets addressLine2
     *
     * @param string $addressLine2 Address Line 2 of the public address
     *
     * @return $this
     */
    public function setAddressLine2($addressLine2)
    {
        $this->container['addressLine2'] = $addressLine2;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city City name of the public address
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state State name of the public address. This is the state or region for China-based addresses.
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets postalCode
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postalCode'];
    }

    /**
     * Sets postalCode
     *
     * @param string $postalCode Postal code of the public address
     *
     * @return $this
     */
    public function setPostalCode($postalCode)
    {
        $this->container['postalCode'] = $postalCode;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country Country name of the public address
     *
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets countryCode
     *
     * @return string
     */
    public function getCountryCode()
    {
        return $this->container['countryCode'];
    }

    /**
     * Sets countryCode
     *
     * @param string $countryCode The two digit country code, in ISO 3166 format.
     *
     * @return $this
     */
    public function setCountryCode($countryCode)
    {
        $this->container['countryCode'] = $countryCode;

        return $this;
    }

    /**
     * Gets emailAddress
     *
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->container['emailAddress'];
    }

    /**
     * Sets emailAddress
     *
     * @param string $emailAddress Email address of the payee.
     *
     * @return $this
     */
    public function setEmailAddress($emailAddress)
    {
        $this->container['emailAddress'] = $emailAddress;

        return $this;
    }

    /**
     * Gets phoneNumber
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->container['phoneNumber'];
    }

    /**
     * Sets phoneNumber
     *
     * @param string $phoneNumber Valid phone number of the payee.
     *
     * @return $this
     */
    public function setPhoneNumber($phoneNumber)
    {
        $this->container['phoneNumber'] = $phoneNumber;

        return $this;
    }

    /**
     * Gets payeeEntityType
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\PayeeEntityType
     */
    public function getPayeeEntityType()
    {
        return $this->container['payeeEntityType'];
    }

    /**
     * Sets payeeEntityType
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\PayeeEntityType $payeeEntityType payeeEntityType
     *
     * @return $this
     */
    public function setPayeeEntityType($payeeEntityType)
    {
        $this->container['payeeEntityType'] = $payeeEntityType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
