<?php
/**
 * TransferSchedule
 *
 * PHP version 5
 *
 * @category Class
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for Amazon Seller Wallet Open Banking API Spec.  For more information, refer to the [Seller Wallet Open Banking API Use Case Guide](doc:seller-wallet-open-banking-api-v2024-03-01-use-case-guide).
 *
 * The Selling Partner API for Seller Wallet (Seller Wallet API) provides financial information that is relevant to a seller's Seller Wallet account. You can obtain financial events, balances, and transfer schedules for Seller Wallet accounts. You can also schedule and initiate transactions.
 *
 * OpenAPI spec version: 2024-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.76
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SellingPartnerApi\Model\SellerWallet20240301;

use \ArrayAccess;
use \SellingPartnerApi\ObjectSerializer;

/**
 * TransferSchedule Class Doc Comment
 *
 * @category Class
 * @description Transfer schedule details and related historical details.
 * @package  SellingPartnerApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TransferSchedule implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TransferSchedule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'transferScheduleId' => 'string',
        'transactionType' => '\SellingPartnerApi\Model\SellerWallet20240301\TransactionType',
        'transactionSourceAccount' => '\SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount',
        'transactionDestinationAccount' => '\SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount',
        'transferScheduleStatus' => '\SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleStatus',
        'transferScheduleInformation' => '\SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleInformation',
        'paymentPreference' => '\SellingPartnerApi\Model\SellerWallet20240301\PaymentPreference',
        'transferScheduleFailures' => '\SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleFailures[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'transferScheduleId' => null,
        'transactionType' => null,
        'transactionSourceAccount' => null,
        'transactionDestinationAccount' => null,
        'transferScheduleStatus' => null,
        'transferScheduleInformation' => null,
        'paymentPreference' => null,
        'transferScheduleFailures' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'transferScheduleId' => 'transferScheduleId',
        'transactionType' => 'transactionType',
        'transactionSourceAccount' => 'transactionSourceAccount',
        'transactionDestinationAccount' => 'transactionDestinationAccount',
        'transferScheduleStatus' => 'transferScheduleStatus',
        'transferScheduleInformation' => 'transferScheduleInformation',
        'paymentPreference' => 'paymentPreference',
        'transferScheduleFailures' => 'transferScheduleFailures'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'transferScheduleId' => 'setTransferScheduleId',
        'transactionType' => 'setTransactionType',
        'transactionSourceAccount' => 'setTransactionSourceAccount',
        'transactionDestinationAccount' => 'setTransactionDestinationAccount',
        'transferScheduleStatus' => 'setTransferScheduleStatus',
        'transferScheduleInformation' => 'setTransferScheduleInformation',
        'paymentPreference' => 'setPaymentPreference',
        'transferScheduleFailures' => 'setTransferScheduleFailures'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'transferScheduleId' => 'getTransferScheduleId',
        'transactionType' => 'getTransactionType',
        'transactionSourceAccount' => 'getTransactionSourceAccount',
        'transactionDestinationAccount' => 'getTransactionDestinationAccount',
        'transferScheduleStatus' => 'getTransferScheduleStatus',
        'transferScheduleInformation' => 'getTransferScheduleInformation',
        'paymentPreference' => 'getPaymentPreference',
        'transferScheduleFailures' => 'getTransferScheduleFailures'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['transferScheduleId'] = isset($data['transferScheduleId']) ? $data['transferScheduleId'] : null;
        $this->container['transactionType'] = isset($data['transactionType']) ? $data['transactionType'] : null;
        $this->container['transactionSourceAccount'] = isset($data['transactionSourceAccount']) ? $data['transactionSourceAccount'] : null;
        $this->container['transactionDestinationAccount'] = isset($data['transactionDestinationAccount']) ? $data['transactionDestinationAccount'] : null;
        $this->container['transferScheduleStatus'] = isset($data['transferScheduleStatus']) ? $data['transferScheduleStatus'] : null;
        $this->container['transferScheduleInformation'] = isset($data['transferScheduleInformation']) ? $data['transferScheduleInformation'] : null;
        $this->container['paymentPreference'] = isset($data['paymentPreference']) ? $data['paymentPreference'] : null;
        $this->container['transferScheduleFailures'] = isset($data['transferScheduleFailures']) ? $data['transferScheduleFailures'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['transferScheduleId'] === null) {
            $invalidProperties[] = "'transferScheduleId' can't be null";
        }
        if ($this->container['transactionType'] === null) {
            $invalidProperties[] = "'transactionType' can't be null";
        }
        if ($this->container['transactionDestinationAccount'] === null) {
            $invalidProperties[] = "'transactionDestinationAccount' can't be null";
        }
        if ($this->container['transferScheduleStatus'] === null) {
            $invalidProperties[] = "'transferScheduleStatus' can't be null";
        }
        if ($this->container['transferScheduleInformation'] === null) {
            $invalidProperties[] = "'transferScheduleInformation' can't be null";
        }
        if ($this->container['transferScheduleFailures'] === null) {
            $invalidProperties[] = "'transferScheduleFailures' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets transferScheduleId
     *
     * @return string
     */
    public function getTransferScheduleId()
    {
        return $this->container['transferScheduleId'];
    }

    /**
     * Sets transferScheduleId
     *
     * @param string $transferScheduleId The unique identifier provided by Amazon to the scheduled transfer
     *
     * @return $this
     */
    public function setTransferScheduleId($transferScheduleId)
    {
        $this->container['transferScheduleId'] = $transferScheduleId;

        return $this;
    }

    /**
     * Gets transactionType
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransactionType
     */
    public function getTransactionType()
    {
        return $this->container['transactionType'];
    }

    /**
     * Sets transactionType
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransactionType $transactionType transactionType
     *
     * @return $this
     */
    public function setTransactionType($transactionType)
    {
        $this->container['transactionType'] = $transactionType;

        return $this;
    }

    /**
     * Gets transactionSourceAccount
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount
     */
    public function getTransactionSourceAccount()
    {
        return $this->container['transactionSourceAccount'];
    }

    /**
     * Sets transactionSourceAccount
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount $transactionSourceAccount transactionSourceAccount
     *
     * @return $this
     */
    public function setTransactionSourceAccount($transactionSourceAccount)
    {
        $this->container['transactionSourceAccount'] = $transactionSourceAccount;

        return $this;
    }

    /**
     * Gets transactionDestinationAccount
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount
     */
    public function getTransactionDestinationAccount()
    {
        return $this->container['transactionDestinationAccount'];
    }

    /**
     * Sets transactionDestinationAccount
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransactionAccount $transactionDestinationAccount transactionDestinationAccount
     *
     * @return $this
     */
    public function setTransactionDestinationAccount($transactionDestinationAccount)
    {
        $this->container['transactionDestinationAccount'] = $transactionDestinationAccount;

        return $this;
    }

    /**
     * Gets transferScheduleStatus
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleStatus
     */
    public function getTransferScheduleStatus()
    {
        return $this->container['transferScheduleStatus'];
    }

    /**
     * Sets transferScheduleStatus
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleStatus $transferScheduleStatus transferScheduleStatus
     *
     * @return $this
     */
    public function setTransferScheduleStatus($transferScheduleStatus)
    {
        $this->container['transferScheduleStatus'] = $transferScheduleStatus;

        return $this;
    }

    /**
     * Gets transferScheduleInformation
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleInformation
     */
    public function getTransferScheduleInformation()
    {
        return $this->container['transferScheduleInformation'];
    }

    /**
     * Sets transferScheduleInformation
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleInformation $transferScheduleInformation transferScheduleInformation
     *
     * @return $this
     */
    public function setTransferScheduleInformation($transferScheduleInformation)
    {
        $this->container['transferScheduleInformation'] = $transferScheduleInformation;

        return $this;
    }

    /**
     * Gets paymentPreference
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\PaymentPreference
     */
    public function getPaymentPreference()
    {
        return $this->container['paymentPreference'];
    }

    /**
     * Sets paymentPreference
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\PaymentPreference $paymentPreference paymentPreference
     *
     * @return $this
     */
    public function setPaymentPreference($paymentPreference)
    {
        $this->container['paymentPreference'] = $paymentPreference;

        return $this;
    }

    /**
     * Gets transferScheduleFailures
     *
     * @return \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleFailures[]
     */
    public function getTransferScheduleFailures()
    {
        return $this->container['transferScheduleFailures'];
    }

    /**
     * Sets transferScheduleFailures
     *
     * @param \SellingPartnerApi\Model\SellerWallet20240301\TransferScheduleFailures[] $transferScheduleFailures Collection that holds Transfer Schedules that has been cancelled or failed due to certain reasons.
     *
     * @return $this
     */
    public function setTransferScheduleFailures($transferScheduleFailures)
    {
        $this->container['transferScheduleFailures'] = $transferScheduleFailures;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
